update runit

diff --git a/runit b/runit
--- a/runit
+++ b/runit
@@ -1,9 +1,31 @@
 #!/bin/bash
-
+#
+# Copyright (c) 2020 Baidu.com,Inc. All Right Reserved
+#
+# Author: cenquanyu@baidu.com
+# Date: 2020/11/10
+#
+# Brief:
+#   runit is a start managment tool for applications.It loads enviroment
+#   variabes from .env file and start applicaitons from Procfile
+# Globals:
+#   PORT COLOR_ARRAY color_idx
+# Arguments:
+#   -c check
+#   -f procfile
+#   -e envfile
+#   -h help
+# Returns:
+#   succ:0
+#   fail:1
 set -a
 set -o pipefail
-color_idx=1
+PORT=8080
 COLOR_ARRAY=('31' '32' '33' '34' '35' '36' '37')
+color_idx=0
+# variable
+procfile=""
+envfile=""
 
 ##############################################################################
 # Brief:
@@ -16,7 +38,7 @@ COLOR_ARRAY=('31' '32' '33' '34' '35' '36' '37')
 #  none
 ##############################################################################
 function usage() {
-    echo "Usage: runit [-c] [-f procfile|Procfile] [-e envfile|.env]
+  echo "Usage: runit [-c] [-f procfile|Procfile] [-e envfile|.env]
     Options:
      -c: Check procfile and envfile
      -e: Load envfile
@@ -24,41 +46,14 @@ function usage() {
      -h: help information
     "
 }
-##############################################################################
-# Brief:
-#  Validate envfile and procfile
-# Globals:
-#  None
-# Arguments:
-#  $1: file style to verify
-#  $2: file name to verify
-# Returns：
-#  succ: 0
-#  fail: 1
-##############################################################################
-function verify() {
-    local file_style="$1"
-    local file_name="$2"
-    if [[ ! -f "${file_name}" ]]; then
-        echo "verify procfile not exists"
-        return 1
-    elif [[ "${file_type}" == "" ]];then
-        echo "Missing file type"
-        return 1
-    fi
-    if [[ "${file_type}" == "procfile" ]];then
-      verify_proc "${file_name}"
-    else
-      verify_env "${file_name}"
-    fi
-}
+
 ##############################################################################
 # Brief:
 #  verify the procfile
 # Globals:
 #  none
 # Arguments:
-#  $1 procfile
+#  procfile
 # Returns:
 #  succ: 0
 #  fail: 1
@@ -67,17 +62,17 @@ function verify_proc() {
     local proc_file="$1"
     local ret_code=0
 
-    while read procline; do
-        if echo "${procline}" | grep -qv ":"; then
-            err_print "This command has no ':' "
+    [[ ! -f "${proc_file}" ]] && err_print "verify procfile not exists" && return 1
+
+    while read nextline ; do
+        if echo "${nextline}" | grep -v ":"; then
+            err_print "no_colon_command"
             continue
         fi
-        proc_name="${procline%%:*}"
-        proc_cmd="${procline#*:}"
-        echo "${proc_name}" | grep -q "[^a-zA-Z0-9_]" && err_print "${proc_name} including invalid chars" && ret_code=1
-        echo "${proc_cmd}" | grep  "&$" && err_print "${proc_cmd}program cannot run in the background" && ret_code=1
+        proc_name="${nextline%%:*}"
+        proc_value="${nextline#*:}"
+        echo "${proc_name}" | grep -q "[^a-zA-Z_]" && err_print "invalid_char" && ret_code=1
     done < <(grep -vE "^[[:space:]]*#" "${proc_file}")
-
     return ${ret_code}
 }
 ##############################################################################
@@ -86,7 +81,7 @@ function verify_proc() {
 # Globals:
 #  none
 # Agruments:
-#  $1 envfile
+#  envfile
 # Returns:
 #  succ: 0
 #  fail: 1
@@ -96,17 +91,16 @@ function verify_env() {
     local ret_code=0
 
     [[ ! -f "${env_file}" ]] && err_print "verify envfile not exists" && return 1
-    while read envline; do
-        if echo "${envline}" | grep -v "="; then
+    while read nextline; do
+        if echo "${nextline}" | grep -v "="; then
             err_print "no_equal_mark"
             continue
         fi
-        env_name="${envline%%=*}"
-        env_val="${envline#*=}"
-        echo "${env_name}" | grep -q "[^a-zA-Z_]" && err_print "${env_name} including invalid_char" && ret_code=1
-        echo "${env_val}" | grep -qE "[[:space:]]" && err_print "${env_val} value contains space" && ret_code=1
+        env_name="${nextline%%=*}"
+        env_value="${nextline#*=}"
+        echo "${env_name}" | grep -q "[^a-zA-Z_]" && err_print "invalid_char" && ret_code=1
+        echo "${env_value}" | grep -qE "[[:space:]]" && err_print "value_have_space" && ret_code=1
     done < <(grep -vE "^[[:space:]]*#" "${env_file}" | grep -v "^$")
-
     return ${ret_code}
 }
 ##############################################################################
@@ -115,33 +109,33 @@ function verify_env() {
 # Globals:
 #  none
 # Arguments:
-#  $1 errinfo
+#  errinfo
 # Returns:
 #  none
 ##############################################################################
 function err_print() {
-    errinfo="$1"
-    echo "${errinfo}"
+  errinfo="$1"
+  echo "${errinfo}"
 }
 
 function log() {
-    local pid_name="$1"
-    local pid_command="$2"
-    local color="$3"
-    local cur_time=$(date +%H:%M:%S)
+  local name="$1"
+  local command="$2"
+  local color="$3"
+  time=$(date +%H:%M:%s)
 
-    printf "\E[${color}m${cur_time} %-6s | " "${pid_name}"
+  printf "\E[${color}m${time} %-7s] | " "${name}"
 
-    tput sgr0
-    echo "  ${pid_command}"
-    return 0
+  tput sgr0
+  echo "${command}"
+  return 0
 }
+
 ##############################################################################
 # Brief:
 #  Perform start command and print log on screen
 # Globals:
 #  COLOR_ARRAY
-#  color_idx
 # Arguments:
 #  $1: proc name
 #  $2: proc command
@@ -152,31 +146,24 @@ function log() {
 function run_command() {
     local proc_name="$1"
     local command="$2"
-    local proc_pid=$!
-    local cur_color="${COLOR_ARRAY[color_idx]}"
+    local cmd_pid=$!
+    local cur_color="${COLOR_ARRAY[$color_idx]}"
     local cmd_port=$(echo "${command}" | grep -e "\$PORT")
 
-    # set 8080 for default PORT
-    if [[ -n "${cmd_port}" ]] && [[ -z "${PORT}" ]];then
-        export PORT=8080
-    fi
+    [[ -n "${cmd_port}" ]] && [[ -z "${PORT}" ]] && PORT=8080
     bash -c "${command}" > >(
-        while read proc_output; do
-            log "${proc_name}" "${proc_output}" "${cur_color}"
+        while read output; do
+            log "${proc_name}" "${output}" "${COLOR}"
         done
     ) 2>&1 &
 
     local output="$(eval echo \"${command}\")"
-    log "${proc_name}" "${output} start with pid ${proc_pid}" "${cur_color}"
-
+    log "${proc_name}" "${output} start with pid ${cmd_pid}" "${cur_color}"
     [[ $? -ne 0 ]] && return 1
-
     [[ -n "${cmd_port}" ]] && PORT=$((${PORT} + 1))
-
     (( color_idx ++ ))
 
     return 0
-
 }
 ##############################################################################
 # Brief:
@@ -184,17 +171,18 @@ function run_command() {
 # Globals:
 #  none
 # Arguments:
-#  $1 envfile
+#  envfile
 # Returns:
 #  succ: 0
 #  fail: 1
 ##############################################################################
 function load_env_file() {
-    local envfile="$1"
-    local env="${envfile:-./.env}"
-    source "${env}"
-    return 0
-
+  set -a
+  local env_file="$1"
+  for env in $(echo "${env_file}"); do
+    [[ -f "${env}" ]] && source "${env}"
+  done
+  return 0
 }
 ##############################################################################
 # Brief:
@@ -202,83 +190,85 @@ function load_env_file() {
 # Globals:
 #  none
 # Arguments:
-#  $1 procfile
+#  procfile
 # Returns:
 #  succ:0
 #  fail:1
 ##############################################################################
+
 function run_procfile() {
     local proc_file="$1"
-    local procfile=${proc_file:-./Procfile}
-    if [[ ! -s "${procfile}" ]]; then
-        echo 'This procfile is not exists'
-        return 1
-    fi
-    for proc_line in `cat ${procfile}`; do
-        if echo "${proc_line}" | grep -qv ":"; then
-            err_print "This command has no ':' "
+    [[ ! -f "${proc_file}" ]] && err_print "this procfile is not exists" && return 1
+    while read line; do
+        if echo "${line}" | grep -qv ":"; then
+            err_print "no_colon_command"
             continue
         fi
-        local procline=`grep -vE '^[[:space:]]*#|^[[:space:]]*$|^$' "${proc_line}"`
-        local name=${procline%%:*}
-        local cmd=${procline#*:}
-        run_command "${name}" "${cmd}"
-        if [[ $? -ne 0 ]];then
-            return 1
-        fi
-    done
-    trap "kill 0" SIGINT SIGTERM
+        local name="${line%%:*}"
+        local cmd="${line#*:}"
+        [[ -n "${name}" ]] && [[ -n "${cmd}" ]] && run_command "${name}" "${cmd}"
+        [[ $? -ne 0 ]] && return 1
+    done < <(grep "" "${proc_file}" | grep -vE "[[:space:]]*#" | grep -v "^$" )
+    wait
     return 0
-
 }
 ##############################################################################
 # Brief:
 #  Main procedure
 # Globals:
-#  procfile encfile
+#  procfile envfile
 # Arguments:
 #  none
 # Returns:
 #  none
 ##############################################################################
 function main() {
-  file_check=false
-  # options
-  while getops ce:f:h opt; do
-      case $opt in
-      c) file_check=true ;;
-      e) envfile="${OPTARG}" ;;
-      f) procfile="${OPTARG}" ;;
-      *) usage ;;
-      esac
+  local check=false
+  while getopts "f:e:ch" OPT; do
+    case ${OPT} in
+    c) check=true ;;
+    f) procfile="${OPTARG}" ;;
+    e) envfile="${OPTARG}" ;;
+    *) usage ;;
+    esac
   done
 
-  # load envfile
-  env="${envfile:-./.env}"
-  load_env_file "${envfile}"
-  if [[ $? -ne 0 ]]; then
+  if ${check}; then
+    if [[ -n "${procfile}" ]]; then
+      verify_proc "${procfile}"
+      proc_ret_code=$?
+      [[ ${proc_ret_code} -ne 0 ]] && exit 1
+    else
+      err_print "The procfile is null"
       exit 1
-  fi
+    fi
 
-  # verify procfile and envfile
-  if ${file_check}; then
-      verify procfile "${procfile}"
-      if [[ $? -ne 0 ]]; then
-          exit 1
-      fi
-      verify envfile "${env}"
-      if [[ $? -ne 0 ]]; then
-          exit 1
-      fi
-      exit 0
-  fi
+    if [[ -z "${envfile}" ]]; then
+      envfile="./.env"
+    fi
+    verify_env "${envfile}"
+    env_ret_code=$?
+    [[ ${env_ret_code} -ne 0 ]] && exit 1
 
-  # run procfile
-  run_procfile "${procfile}"
-  if [[ $? -ne 0 ]]; then
-      exit 1
-  fi
+  else
+    if [[ -z "${envfile}" ]]; then
+      envfile="./.env"
+    fi
 
+    load_env_file "${envfile}"
+    load_env_ret_code=$?
+    [[ ${load_env_ret_code} -ne 0 ]] && exit 1
+
+    if [[ -z "${procfile}" ]]; then
+      procfile="./Procfile"
+    fi
+
+    run_procfile "${procfile}"
+    run_ret_code=$?
+    [[ run_ret_code -ne 0 ]] && exit 1
+  fi
+  exit 0
 }
 
 main "$@"
+
